# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: v1/seatsaver.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import v1.seatsaver_pb2


class SeatSaverServiceBase(abc.ABC):

    @abc.abstractmethod
    async def GetVenues(self, stream: 'grpclib.server.Stream[v1.seatsaver_pb2.GetVenuesRequest, v1.seatsaver_pb2.GetVenuesResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GetVenue(self, stream: 'grpclib.server.Stream[v1.seatsaver_pb2.GetVenueRequest, v1.seatsaver_pb2.GetVenueResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GetOpenSeats(self, stream: 'grpclib.server.Stream[v1.seatsaver_pb2.GetOpenSeatsRequest, v1.seatsaver_pb2.GetOpenSeatsResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GetSoldSeats(self, stream: 'grpclib.server.Stream[v1.seatsaver_pb2.GetSoldSeatsRequest, v1.seatsaver_pb2.GetSoldSeatsResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GetReservedSeats(self, stream: 'grpclib.server.Stream[v1.seatsaver_pb2.GetReservedSeatsRequest, v1.seatsaver_pb2.GetReservedSeatsResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GetSeats(self, stream: 'grpclib.server.Stream[v1.seatsaver_pb2.GetSeatsRequest, v1.seatsaver_pb2.GetSeatsResponse]') -> None:
        pass

    @abc.abstractmethod
    async def ReserveSeat(self, stream: 'grpclib.server.Stream[v1.seatsaver_pb2.ReserveSeatRequest, v1.seatsaver_pb2.ReserveSeatResponse]') -> None:
        pass

    @abc.abstractmethod
    async def ReleaseSeat(self, stream: 'grpclib.server.Stream[v1.seatsaver_pb2.ReleaseSeatRequest, v1.seatsaver_pb2.ReleaseSeatResponse]') -> None:
        pass

    @abc.abstractmethod
    async def BuySeat(self, stream: 'grpclib.server.Stream[v1.seatsaver_pb2.BuySeatRequest, v1.seatsaver_pb2.BuySeatResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Ping(self, stream: 'grpclib.server.Stream[v1.seatsaver_pb2.PingRequest, v1.seatsaver_pb2.PingResponse]') -> None:
        pass

    @abc.abstractmethod
    async def PingStream(self, stream: 'grpclib.server.Stream[v1.seatsaver_pb2.PingStreamRequest, v1.seatsaver_pb2.PingStreamResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/grpc.seatsaver.v1.SeatSaverService/GetVenues': grpclib.const.Handler(
                self.GetVenues,
                grpclib.const.Cardinality.UNARY_STREAM,
                v1.seatsaver_pb2.GetVenuesRequest,
                v1.seatsaver_pb2.GetVenuesResponse,
            ),
            '/grpc.seatsaver.v1.SeatSaverService/GetVenue': grpclib.const.Handler(
                self.GetVenue,
                grpclib.const.Cardinality.UNARY_UNARY,
                v1.seatsaver_pb2.GetVenueRequest,
                v1.seatsaver_pb2.GetVenueResponse,
            ),
            '/grpc.seatsaver.v1.SeatSaverService/GetOpenSeats': grpclib.const.Handler(
                self.GetOpenSeats,
                grpclib.const.Cardinality.UNARY_STREAM,
                v1.seatsaver_pb2.GetOpenSeatsRequest,
                v1.seatsaver_pb2.GetOpenSeatsResponse,
            ),
            '/grpc.seatsaver.v1.SeatSaverService/GetSoldSeats': grpclib.const.Handler(
                self.GetSoldSeats,
                grpclib.const.Cardinality.UNARY_STREAM,
                v1.seatsaver_pb2.GetSoldSeatsRequest,
                v1.seatsaver_pb2.GetSoldSeatsResponse,
            ),
            '/grpc.seatsaver.v1.SeatSaverService/GetReservedSeats': grpclib.const.Handler(
                self.GetReservedSeats,
                grpclib.const.Cardinality.UNARY_STREAM,
                v1.seatsaver_pb2.GetReservedSeatsRequest,
                v1.seatsaver_pb2.GetReservedSeatsResponse,
            ),
            '/grpc.seatsaver.v1.SeatSaverService/GetSeats': grpclib.const.Handler(
                self.GetSeats,
                grpclib.const.Cardinality.UNARY_STREAM,
                v1.seatsaver_pb2.GetSeatsRequest,
                v1.seatsaver_pb2.GetSeatsResponse,
            ),
            '/grpc.seatsaver.v1.SeatSaverService/ReserveSeat': grpclib.const.Handler(
                self.ReserveSeat,
                grpclib.const.Cardinality.UNARY_UNARY,
                v1.seatsaver_pb2.ReserveSeatRequest,
                v1.seatsaver_pb2.ReserveSeatResponse,
            ),
            '/grpc.seatsaver.v1.SeatSaverService/ReleaseSeat': grpclib.const.Handler(
                self.ReleaseSeat,
                grpclib.const.Cardinality.UNARY_UNARY,
                v1.seatsaver_pb2.ReleaseSeatRequest,
                v1.seatsaver_pb2.ReleaseSeatResponse,
            ),
            '/grpc.seatsaver.v1.SeatSaverService/BuySeat': grpclib.const.Handler(
                self.BuySeat,
                grpclib.const.Cardinality.UNARY_UNARY,
                v1.seatsaver_pb2.BuySeatRequest,
                v1.seatsaver_pb2.BuySeatResponse,
            ),
            '/grpc.seatsaver.v1.SeatSaverService/Ping': grpclib.const.Handler(
                self.Ping,
                grpclib.const.Cardinality.UNARY_UNARY,
                v1.seatsaver_pb2.PingRequest,
                v1.seatsaver_pb2.PingResponse,
            ),
            '/grpc.seatsaver.v1.SeatSaverService/PingStream': grpclib.const.Handler(
                self.PingStream,
                grpclib.const.Cardinality.UNARY_STREAM,
                v1.seatsaver_pb2.PingStreamRequest,
                v1.seatsaver_pb2.PingStreamResponse,
            ),
        }


class SeatSaverServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.GetVenues = grpclib.client.UnaryStreamMethod(
            channel,
            '/grpc.seatsaver.v1.SeatSaverService/GetVenues',
            v1.seatsaver_pb2.GetVenuesRequest,
            v1.seatsaver_pb2.GetVenuesResponse,
        )
        self.GetVenue = grpclib.client.UnaryUnaryMethod(
            channel,
            '/grpc.seatsaver.v1.SeatSaverService/GetVenue',
            v1.seatsaver_pb2.GetVenueRequest,
            v1.seatsaver_pb2.GetVenueResponse,
        )
        self.GetOpenSeats = grpclib.client.UnaryStreamMethod(
            channel,
            '/grpc.seatsaver.v1.SeatSaverService/GetOpenSeats',
            v1.seatsaver_pb2.GetOpenSeatsRequest,
            v1.seatsaver_pb2.GetOpenSeatsResponse,
        )
        self.GetSoldSeats = grpclib.client.UnaryStreamMethod(
            channel,
            '/grpc.seatsaver.v1.SeatSaverService/GetSoldSeats',
            v1.seatsaver_pb2.GetSoldSeatsRequest,
            v1.seatsaver_pb2.GetSoldSeatsResponse,
        )
        self.GetReservedSeats = grpclib.client.UnaryStreamMethod(
            channel,
            '/grpc.seatsaver.v1.SeatSaverService/GetReservedSeats',
            v1.seatsaver_pb2.GetReservedSeatsRequest,
            v1.seatsaver_pb2.GetReservedSeatsResponse,
        )
        self.GetSeats = grpclib.client.UnaryStreamMethod(
            channel,
            '/grpc.seatsaver.v1.SeatSaverService/GetSeats',
            v1.seatsaver_pb2.GetSeatsRequest,
            v1.seatsaver_pb2.GetSeatsResponse,
        )
        self.ReserveSeat = grpclib.client.UnaryUnaryMethod(
            channel,
            '/grpc.seatsaver.v1.SeatSaverService/ReserveSeat',
            v1.seatsaver_pb2.ReserveSeatRequest,
            v1.seatsaver_pb2.ReserveSeatResponse,
        )
        self.ReleaseSeat = grpclib.client.UnaryUnaryMethod(
            channel,
            '/grpc.seatsaver.v1.SeatSaverService/ReleaseSeat',
            v1.seatsaver_pb2.ReleaseSeatRequest,
            v1.seatsaver_pb2.ReleaseSeatResponse,
        )
        self.BuySeat = grpclib.client.UnaryUnaryMethod(
            channel,
            '/grpc.seatsaver.v1.SeatSaverService/BuySeat',
            v1.seatsaver_pb2.BuySeatRequest,
            v1.seatsaver_pb2.BuySeatResponse,
        )
        self.Ping = grpclib.client.UnaryUnaryMethod(
            channel,
            '/grpc.seatsaver.v1.SeatSaverService/Ping',
            v1.seatsaver_pb2.PingRequest,
            v1.seatsaver_pb2.PingResponse,
        )
        self.PingStream = grpclib.client.UnaryStreamMethod(
            channel,
            '/grpc.seatsaver.v1.SeatSaverService/PingStream',
            v1.seatsaver_pb2.PingStreamRequest,
            v1.seatsaver_pb2.PingStreamResponse,
        )
